version: 2
jobs:
  build:
    docker:
      - image: dockeredwin94/authservice
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: install-npm-wee
          command: npm install
     
